name: scaling_button_widget
description: A Flutter widget that creates a button that scales down slightly when pressed and returns to its original size when released.
version: 0.0.1
homepage:
license: MIT

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
